language: java
jdk:
  - oraclejdk8
before_install:
    - wget https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_i386.deb
    - sudo dpkg -i hugo_0.15_i386.deb
script:
    - mvn -f Tests -DliveTest=false test
    - mvn -f Tests -DliveTest=true test
