baseurl = "http://www.baskinginthesun.co.uk"
languageCode = "ja-jp"
title = "ひなたぼっこ"

[params]
topimage = "http://images.baskinginthesun.co.uk/shutterstock_134583743.jpg"
contactformaction = "http://forms.brace.io/alangibson27@gmail.com"
calendarurl = "1fb7aiiosv3bs1mtbi6n2qqhvk@group.calendar.google.com"