baseurl = "http://www.baskinginthesun.co.uk"
languageCode = "ja-jp"
title = "ひなたぼっこ"

[params]
topimage = "http://images.baskinginthesun.co.uk/shutterstock_134583743.jpg"
contactformaction = "http://forms.brace.io/baskinginthesun22@gmail.com"
calendarurl = "opi0pnshql48d9u8ssmrovpr00@group.calendar.google.com"
