baseurl = "http://www.baskinginthesun.co.uk"
languageCode = "ja-jp"
title = "ひなたぼっこ"

[params]
logo = "http://images.baskinginthesun.co.uk/logo.jpg"
calendarurl = "opi0pnshql48d9u8ssmrovpr00@group.calendar.google.com"
