baseurl = "http://www.baskinginthesun.co.uk"
DefaultContentLanguage="ja"

[params]
logo = "http://images.baskinginthesun.co.uk/logo.jpg"
calendarurl = "opi0pnshql48d9u8ssmrovpr00@group.calendar.google.com"

[Languages]
[Languages.ja]
title = "ひなたぼっこ"
LanguageName = "日本語"

[Languages.en]
title = "Basking in the Sun"
LanguageName = "English"
